name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
          /home/runner/go/bin/golangci-lint run --out-format checkstyle > /home/runner/golangci.xml
          cat /home/runner/golangci.xml
      - name: upload report
        uses: actions/upload-artifect@v3
        with:
          name: golangci.xml
          path: /home/runner/golangci.xml
job:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: download report
        uses: actions/download-artifact@v3
        with:
          name: golangci.xml

      - uses: warchant/setup-sonar-scanner@v3
      - name: run sonar scanner
        run: sonar-scanner -Dsonar.organization=dhaval070 -Dsonar.projectKey=dhaval070 -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.go.golangci-lint.reportPaths=golangci.xml
